<?php
/**
 * This class has been auto-generated by PHP-DI.
 */
class CompiledContainer extends DI\CompiledContainer{
    const METHOD_MAPPING = array (
  'amir' => 'get1',
  'GetCompanyByBusinessIdService' => 'get2',
);

    protected function get1()
    {
        $object = new Isolta\OpenData\Formatter\ResultToBusinessFormatter();
        return $object;
    }

    protected function get2()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $container) {
        return new \Isolta\OpenData\Service\GetCompanyByBusinessIdService($container->get('amir'));
    }, 'GetCompanyByBusinessIdService');
    }

}
